[versions]
hec-monolith = "6.0.0-rc02"
sqliteJdbc = "3.45.3.0"
service-annotations = "2.0.1"

# Natives
heclib = "7-IU-5"

# Third Party

# Test

[libraries]
hec-monolithbom = { module = "mil.army.usace.hec:hec-monolith-bom", version.ref = "hec-monolith" }
hec-monolith = { module = "mil.army.usace.hec:hec-monolith", version.ref = "hec-monolith" }
sqliteJdbc = {module = "org.xerial:sqlite-jdbc", version.ref = "sqliteJdbc" }
service-annotations = { module = "mil.army.usace.hec:service-annotations", version.ref = "service-annotations" }

# Natives
heclib = { module = "mil.army.usace.hec:javaHeclib" }

# Third Party

# Test

[bundles]
hec-monolith = ["hec-monolith"]

# Third party
