[versions]
hec-monolith = "7.0.4"
sqliteJdbc = "3.45.3.0"
heclib = "7-JA-5-win-x86_64"
org-slf4j = "1.7.36"
jetbrainsAnnotations = "24.1.0"
junitBom = "5.10.0"

[libraries]
hec-monolith = { module = "mil.army.usace.hec:hec-monolith", version.ref = "hec-monolith" }
sqliteJdbc = {module = "org.xerial:sqlite-jdbc", version.ref = "sqliteJdbc" }
heclib = { module = "mil.army.usace.hec:javaHeclib", version.ref = "heclib" }
org-slf4j = { module = "org.slf4j:slf4j-simple", version.ref = "org-slf4j" }
jetbrainsAnnotations = { module = "org.jetbrains:annotations", version.ref = "jetbrainsAnnotations" }
junitBom = { module = "org.junit:junit-bom", version.ref = "junitBom" }
junitJupiter = { module = "org.junit.jupiter:junit-jupiter" }
junitPlatformLauncher = { module = "org.junit.platform:junit-platform-launcher" }
